#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Identify the package manager based on lock file presence
if [ -f "pnpm-lock.yaml" ]; then
  CL_CMD="pnpm commitlint"
  LS_CMD="pnpm lint-staged"
elif [ -f "yarn.lock" ]; then
  CL_CMD="yarn commitlint"
  LS_CMD="yarn lint-staged"
else
  CL_CMD="npm run commitlint"
  LS_CMD="npm run lint-staged"
fi

echo "🔎 Checking the commit message..."
$CL_CMD || false

echo "📝 Checking types, linting, and formatting before committing..."
$LS_CMD ||
(
  echo "❌ Failed. Lint, add changes, and try committing again";
  false;
)
